### ISSUE TITLE
OOM Exception with WebP Images

### ISSUE THREAD

**Issue by CaptMustache** [paolorotolo/AppIntro#357] opened 2016-11-17 19:33 UTC
Using the latest version 4.1.0 it is not possible to use WebP images. 
The app crashes with an OOM error:

W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (2556x5124, max=4096x4096)
java.lang.OutOfMemoryError: Failed to allocate a 52387788 byte allocation with 16777216 free bytes and 37MB until OOM

Used image size: 852x1708

**Comment by avluis** [comment] 2016-11-17 19:36
Have you tried loading this image in a standard image widget without making use of the library?
I mean, the issue is fairly obvious.

**Comment by Andrew-Quebe** [comment] 2016-11-17 19:41
@CaptMustache please provide code! Did you completely ignore the issue template?

**Comment by Andrew-Quebe** [comment] 2016-11-23 07:45
@CaptMustache closing until you update us. Reopen if your issue persists, and include code.

**Closed by Andrew-Quebe** 2016-11-23 07:45 UTC
Labels: under investigation
