### ISSUE TITLE
Title font is diferent than shown in Screenshots.

### ISSUE THREAD

**Issue by blushmaq** [PaoloRotolo/AppIntro#162] opened 2016-01-29 20:40 UTC
Actually I'm not much familiar with the way libraries work and how to use them. But as far as I know I've followed steps correctly. Though I'm seeing a different bold font than the one shown in Screenshots. 

I was also not able to change the colors but saw the open issues and found a workaround.So I'm left with the font issue and the animation issue. Please guide me to the solutions if I'm missing them. Thank you.

**Comment by jordanleeproductions** [comment] 2016-02-07 19:18
You aren't the only one, I am also having the same issue.. I am unable to change the Title and Description text's Typeface. 

I found I could only set the background colour by parsing the hex value:
`Color.parseColor("#5d9cec")`
and not by referencing the Color resource value.

**Comment by avluis** [comment] 2016-04-22 00:33
Depending on how you are creating your layouts, you need to set the fontFamily for the element you wish to modify, [here](http://stackoverflow.com/a/13329907/1615876) is an example of how to do just that.

Is the library overriding the values set in your xml?

**Comment by m-jaekel** [comment] 2016-04-28 09:37
The problem is, when one is just using "addSlide(AppIntroFragment.newInstance(title, description, image, background_colour));" to add new slides how to access the xml to change those attributes.

**Comment by avluis** [comment] 2016-04-28 13:13
I see - I am using addSlide as well, but with a `BaseSlide` fragment, which lets you override those things a lot easier.
Let me take a good look at `AppIntroFragment` and see if I can give you a workaround.

**Comment by Prawesome** [comment] 2016-07-13 13:31
Would like to add that I am also facing the same issues while using addSlide().

**Comment by avluis** [comment] 2016-08-24 04:31
New changes to the library target this issue specifically -- would need to wait for release in order for this issue to be marked closed, so this comment is here as a reminder of that--

**Comment by Andrew-Quebe** [comment] 2016-09-26 16:59
@avluis can we close this now?

**Comment by avluis** [comment] 2016-09-26 17:06
@Andrew-Quebe Definitely can -- while the update for the library is not yet out, this has been technically addressed.

**Closed by avluis** 2016-09-26 17:06 UTC
Labels: question, under investigation

**Comment by Andrew-Quebe** [comment] 2016-09-26 17:08
@avluis and @everyone, I'll shoot @PaoloRotolo a message for him to update the lib.
