### ISSUE TITLE
NullPointerException in onCreate() from README code

### ISSUE THREAD

**Issue by bogomazov** [PaoloRotolo/AppIntro#281] opened 2016-08-18 02:55 UTC
[ ] What you've tried (include code snippets, or whole files as necessary):

Just wrote starting code from README tutorial. Getting null pointer exception inside of super.onCreate()

[ ] What you thought should happen:

Should gracefully work.

[ ] What actually happened:

```txt
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                       at com.github.paolorotolo.appintro.AppIntroBase.onCreate(AppIntroBase.java:92)
                                                                       at com.bogomazz.reachr.Login.Intro.Intro.onCreate(Intro.java:19)
```
Hope it helps.

**Comment by avluis** [comment] 2016-08-18 03:25
Is your code extending AppIntro or AppIntro2 -- can I see your xml if you are using your own?

**Comment by bogomazov** [comment] 2016-08-18 03:29
AppIntro. I didn't add any xml layouts.

**Comment by avluis** [comment] 2016-08-18 03:30
Got it -- can I see your code for the Activity extending AppIntro?

**Comment by bogomazov** [comment] 2016-08-18 03:32
The only difference from what you have in README are these lines where I add Slides.
addSlide(AppIntroFragment.newInstance(discoverTitle, discoverDescription, R.drawable.ic_discover, R.color.aqua_blue));
        addSlide(AppIntroFragment.newInstance(discoverTitle, discoverDescription, R.drawable.ic_discover, R.color.aqua_blue));
I guess I should be passing wrong values?

**Comment by avluis** [comment] 2016-08-18 03:41
Ah, yes -- give me a minute to start up Android Studio to verify.
The library is in need of a few more annotations (I recently pushed a PR to address a few of these).
It looks like you are passing an xml value for drawable, instead of an actual int value -- let me double check.

**Comment by avluis** [comment] 2016-08-18 03:47
Here we go, this is what addSlide is expecting:

```java
addSlide(AppIntroFragment.newInstance("Title here", "Description here",R.drawable.ic_slide1, Color.parseColor("#2196F3")));
```

**Comment by bogomazov** [comment] 2016-08-18 03:52
Thank you. I will check it out!

**Comment by avluis** [comment] 2016-08-18 03:56
Make certain to check the GitHub website, since edits to my comments don't get forwarded to your email.

**Comment by bogomazov** [comment] 2016-08-19 01:29
Hi, it still crashes in parent constructor. 

Gradle:

```
repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.github.paolorotolo:appintro:4.0.0'
 ...
```
```
package com.bogomazz.reachr.Login.Intro;

import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;

import com.bogomazz.reachr.R;
import com.github.paolorotolo.appintro.AppIntro;
import com.github.paolorotolo.appintro.AppIntroFragment;

/**
 * Created by andrey on 8/17/16.
 */
public class Intro extends AppIntro {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Add your slide's fragments here.
        // AppIntro will automatically generate the dots indicator and buttons.
//        addSlide(first_fragment);
//        addSlide(second_fragment);
//        addSlide(third_fragment);
//        addSlide(fourth_fragment);

        // Instead of fragments, you can also use our default slide
        // Just set a title, description, background and image. AppIntro will do the rest.
        String discoverTitle = "Title!";
        String discoverDescription = "Description!";
        addSlide(AppIntroFragment.newInstance(discoverTitle, discoverDescription, R.drawable.ic_discover, Color.parseColor("#2196F3")));
        addSlide(AppIntroFragment.newInstance(discoverTitle, discoverDescription, R.drawable.ic_discover, Color.parseColor("#2196F3")));

        // OPTIONAL METHODS
        // Override bar/separator color.
        setBarColor(Color.parseColor("#3F51B5"));
        setSeparatorColor(Color.parseColor("#2196F3"));

        // Hide Skip/Done button.
        showSkipButton(false);
        setProgressButtonEnabled(false);

        // Turn vibration on and set intensity.
        // NOTE: you will probably need to ask VIBRATE permisssion in Manifest.
        setVibrate(true);
        setVibrateIntensity(30);
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        // Do something when users tap on Skip button.
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        // Do something when users tap on Done button.
    }

    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        // Do something when the slide changes.
    }
}
```

**Comment by avluis** [comment] 2016-08-19 02:12
Are your sources accessible online?
If they are not private or closed sourced, is it possible to post your repo or a compressed zip here?

**Comment by bogomazov** [comment] 2016-08-19 03:05
Sorry, the project is private.
There is some of customization in theme such as disabled action bar. Let me
know if any environment variables can affect the way Intro is constructed
which I could check.
Thank you!

**Comment by avluis** [comment] 2016-08-19 05:57
There shouldn't be any issues if you are simply passing the right arguments to the `AppIntroFragment.newInstance()` constructor.

Lets try this -- can you download the repo locally and run the example app in your development environment -- this would let us know if there is anything else going on.
As of right now, the only change the repo needs to run is updating gradle - which Android Studio should handle for you with no issue.

Please let me know what are your results when you try this.

**Comment by avluis** [comment] 2016-08-23 04:30
@bogomazov Any changes?

**Comment by bogomazov** [comment] 2016-08-23 12:20
I will check today and get back to you.
Thank you.

**Comment by avluis** [comment] 2016-09-14 22:50
Closing -- no reply -- not able to reproduce.
Please re-open whenever you like it.

**Closed by avluis** 2016-09-14 22:50 UTC
Labels: under investigation
