### ISSUE TITLE
Change the next slide depending on the result of askForPermissions 

### ISSUE THREAD

**Issue by PadronFroyo** [PaoloRotolo/AppIntro#173] opened 2016-02-14 14:42 UTC
It would be very useful to be able to change a slide (or the content of a slide) depending on the reslult of askForPermissions  method. So if the user doesn't grant the permission I can show a slide to alert that without that permission the app will not work properly.

Regards,

Simone

**Comment by Andrew-Quebe** [comment] 2016-03-02 09:28
Duplicate of #115.

**Closed by Andrew-Quebe** 2016-03-02 09:28 UTC
