### ISSUE TITLE
Is it possible to get data from those fragments

### ISSUE THREAD

**Issue by sunil512** [PaoloRotolo/AppIntro#225] opened 2016-05-19 08:20 UTC
Hi, I used AppIntro it was nice, actually I designed my own custom fragment and added to MyIntro class(which extends AppIntro). Here in my custom fragment I added a edit text and sub radiobuttons, when I pressed on done or Get started I want data from edit text, is it possible to get the data from the fragments.

**Comment by avluis** [comment] 2016-05-19 10:03
Have you tried passing that information in a bundle?
This is usually how you would pass information between activities, so make sure your fragment is collecting and sending this data to the attached activity.

**Comment by sunil512** [comment] 2016-05-19 10:27
See actually as in your documentation the getStarted() and done methods are in separate class called MyIntro. in my custom fragment I added edittext and buttons by clicking on done or get started. my code should implement and get data from fragment to my mainActivity. but those getStarted and done methods are not in my added fragment class they are in MyIntro class.                                                                                                               Here we are calling click event in MyIntro class not in fragment class. How to get my edittext and button to the MyIntro. where to implement the logic either in my custom fragment or in the MyIntro class ? as per the documentation MainActivity is called in MyIntro class.

**Comment by avluis** [comment] 2016-05-19 10:37
Android coding guidelines recommends passing data from a Fragment to the hosting Activity, which can then pass the data in whatever is most appropriate.

So if I'm understanding this right:
MyIntro extends AppIntro, which adds a slide with a Fragment that contains your EditText and other widgets.
Therefore, you need to either:
Implement an Interface to pass data or access your Activity's methods via getActivity() in your Fragment. [Ref](http://stackoverflow.com/questions/9343241/passing-data-between-a-fragment-and-its-container-activity).

Once the data has been passed, either via the Interface (which the Activity can then query) or via a method in your Activity, you can then pass this data where needed.

Does that clarify your issue?

**Comment by sunil512** [comment] 2016-05-19 10:39
`
`![capture](https://cloud.githubusercontent.com/assets/14230000/15390876/e84e2e6e-1ddb-11e6-8ad9-7b8ce3d8498a.PNG)`

above Image shows my custom fragment

``
`

**Comment by avluis** [comment] 2016-05-19 10:42
That doesn't tell me anything, please post the code associated with this.
I need to see what powers this view~ :battery:

**Comment by sunil512** [comment] 2016-05-19 10:51
This is  class
`public final class MyIntro extends AppIntro {

    @Override
    public void init(Bundle savedInstanceState) {
        addSlide(SampleSlide.newInstance(R.layout.fragmenta));
        addSlide(SampleSlide.newInstance(R.layout.fragmentb));
        addSlide(SampleSlide.newInstance(R.layout.fragmentc));
    }

    @Override
    public void onSkipPressed() {
        loadMainActivity();
        Toast.makeText(getApplicationContext(), getString(R.string.skip), Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onNextPressed() {

    }

    @Override
    public void onDonePressed() {

    }

    @Override
    public void onSlideChanged() {

    }

    private void loadMainActivity() {
        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
    }

    public void getStarted(View v) {

    }
}`


`EditText ed;
    RadioButton rb1,rb2;`

 if (!ed.getText().toString().equals("")) {
            if (rb1.isChecked()) {
                int input = Integer.valueOf(ed.getText().toString());
                double out = input / 24.0;
                out = Double.parseDouble(new DecimalFormat("#.0").format(out));
                Intent m = new Intent(getActivity(), MainActivity.class);
                m.putExtra("res", out);
                startActivity(m);
            } else if (rb2.isChecked()) {
                int input = Integer.valueOf(ed.getText().toString());
                double out = ((input * 2 / 3) * 0.029574);
                out = Double.parseDouble(new DecimalFormat("#.0").format(out));
                Intent m = new Intent(getActivity(), MainActivity.class);
                m.putExtra("res", out);
                startActivity(m);
            }


I have to add above code, how to send that data to MainActivity

**Comment by sunil512** [comment] 2016-05-19 10:52
it should be send by main activity but the methods are in MyIntro class. so, how send that data to main activity.

**Comment by avluis** [comment] 2016-05-19 11:06
If I am reading this right - the white space seems to have been nuked, then you are creating an intent already - so, all you need to do now is to check for data in the target Activity.

**Comment by sunil512** [comment] 2016-05-19 11:51
you didn't get me .

MyIntro class
`public final class MyIntro extends AppIntro {

    @Override
    public void init(Bundle savedInstanceState) {
        addSlide(SampleSlide.newInstance(R.layout.fragmenta));
        addSlide(SampleSlide.newInstance(R.layout.fragmentb));
        addSlide(SampleSlide.newInstance(R.layout.fragmentc));
    }

    @Override
    public void onSkipPressed() {
        loadMainActivity();
        Toast.makeText(getApplicationContext(), getString(R.string.skip), Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onNextPressed() {

    }

    @Override
    public void onDonePressed() {

    }

    @Override
    public void onSlideChanged() {

    }

    private void loadMainActivity() {
        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
    }

    public void getStarted(View v) {

    }
}
`

My custom fragmentc class

`public class Fragmentc extends Fragment {

    EditText ed;
    RadioButton rb1,rb2;

    public Fragmentc() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View v = inflater.inflate(R.layout.fragmentc, container, false);
        ed = (EditText) v.findViewById(R.id.editText);
        rb1 = (RadioButton) v.findViewById(R.id.radioButton1);
        rb2 = (RadioButton) v.findViewById(R.id.radioButton2);
        return v;
    }
`

when user clicks on GetStarted or Done in the third fragmentc. My logic implements and send data to MainActivity, so, logic should be in these two methods below in MyIntro.
my logic is:

`if (!ed.getText().toString().equals("")) {
            if (rb1.isChecked()) {
                int input = Integer.valueOf(ed.getText().toString());
                double out = input / 24.0;
                out = Double.parseDouble(new DecimalFormat("#.0").format(out));
                Intent m = new Intent(getActivity(), MainActivity.class);
                m.putExtra("res", out);
                startActivity(m);`

the above code should be added to these two methods below in MyIntro ,but the edittext and buttons are of my custom fragment so it'll show error.

methods in MyIntro:

` @Override
    public void onDonePressed() {

    }`

` public void getStarted(View v) {

    }` methods in MyIntro class.


`@Override
    public void onDonePressed() {
if (!ed.getText().toString().equals("")) {
            if (rb1.isChecked()) {
                int input = Integer.valueOf(ed.getText().toString());
                double out = input / 24.0;
                out = Double.parseDouble(new DecimalFormat("#.0").format(out));
                Intent m = new Intent(getActivity(), MainActivity.class);
                m.putExtra("res", out);
                startActivity(m);
    }`
if I added above code, it'll show error..

Here, we cannot send data to the MainActivity. can we implement my logic in fragment class,I think its not possible  because the onDonePressed and getStarted Methods are in MyInto class.

is there any solution with you.

**Comment by avluis** [comment] 2016-05-19 12:33
@Andrew-Quebe 
Can you explain this better than me? I don't think I know enough English to explain this better than what I have so far.

**Comment by Andrew-Quebe** [comment] 2016-05-19 16:54
Well, at first glance, you're not using the Intro activity correctly. The Intro should be launched as an Intent FROM your MainActivity rather than the other way around. You can simply call `finish()` in the `loadMainActivity()` method to close the intent you launched from the main activity. When it finishes, you'll be taken back to the activity that launched the intent.

Secondly, you've repetitively said it'll show an error, but you haven't given us your error at all. You've written code that seemingly works fine, so I don't see what the issue is. Please copy your errors that you're getting and we can see if we can help you better.

(I edited your comment and formatted the code properly.)

**Comment by sunil512** [comment] 2016-05-20 06:31
Yeah sure @Andrew-Quebe 

my Into class I created

MyIntro:

`public final class MyIntro extends AppIntro {

    EditText ed;
    RadioButton rb1,rb2;

    @Override
    public void init(Bundle savedInstanceState) {
        addSlide(SampleSlide.newInstance(R.layout.fragmenta));
        addSlide(SampleSlide.newInstance(R.layout.fragmentb));
        addSlide(SampleSlide.newInstance(R.layout.fragmentc));

        ed = (EditText) findViewById(R.id.editText);
        rb1 = (RadioButton) findViewById(R.id.radioButton1);
        rb2 = (RadioButton) findViewById(R.id.radioButton2);
    }

    @Override
    public void onSkipPressed() {
        loadMainActivity();
        Toast.makeText(getApplicationContext(), getString(R.string.skip), Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onNextPressed() {

    }

    @Override
    public void onDonePressed() {
    loadMainActivity();
    }

    @Override
    public void onSlideChanged() {

    }

    private void loadMainActivity() {
        if (!ed.getText().toString().equals("")) {
            if (rb1.isChecked()) {
                int input = Integer.valueOf(ed.getText().toString());
                double out = input / 24.0;
                out = Double.parseDouble(new DecimalFormat("#.0").format(out));
                Intent m = new Intent(this, MainActivity.class);
                m.putExtra("res", out);
                startActivity(m);
            } else if (rb2.isChecked()) {
                int input = Integer.valueOf(ed.getText().toString());
                double out = ((input * 2 / 3) * 0.029574);
                out = Double.parseDouble(new DecimalFormat("#.0").format(out));
                Intent m = new Intent(this, MainActivity.class);
                m.putExtra("res", out);
                startActivity(m);
            }
        }
    }

    public void getStarted(View v) {
        loadMainActivity();
    }
}`

Here my intention is to send a double to main activity when I click on Get Started and Done Pressed in fragmentc. as shown below when clicked on Get Started.


![capture](https://cloud.githubusercontent.com/assets/14230000/15419208/296e7600-1e82-11e6-93c1-bdd044dc7ab4.PNG)

but I getting exception.



`AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
AndroidRuntime:     at com.cloudicalabs.waterfinder.waterfinder.activities.MyIntro.loadMainActivity(MyIntro.java:54)
05-20 02:29:44.061 16340-16340/com.cloudicalabs.waterfinder.waterfinder E/AndroidRuntime:     at com.cloudicalabs.waterfinder.waterfinder.activities.MyIntro.getStarted(MyIntro.java:74)`

**Comment by avluis** [comment] 2016-05-20 15:05
Well - I'm not sure how else I can say this, but I will, because that is the way people learn.
What you are attempting to do, while out of scope from the library, meaning it is not an issue with the library, it is simply a matter of implementation.

I cannot give you a tutorial on how to do this, but I will share the following;
AppIntro makes use of Fragments for its slides (I assume you know this since you are using it, but your code contradicts that), so:

- [Study up on fragments](https://developer.android.com/guide/components/fragments.html) and how to [communicate with them via your Activity](https://developer.android.com/guide/components/fragments.html#CommunicatingWithActivity) or between [other components](https://developer.android.com/training/basics/fragments/communicating.html).
- [Add null checks to your code](http://stackoverflow.com/a/12133431/1615876) - assume users are dumb, cover your tracks.

I'm feeling generous, so here are a few tips;

This should be in your fragment, not the activity:

```java
public void getStarted(View v) {
        loadMainActivity();
    }
```
 The fragment is hosting those UI elements, not the activity, so you must access them properly.

Additionally, the following elements will not be able to access the fields in the fragment from the activity:

```java
private void loadMainActivity() {
        if (!ed.getText().toString().equals("")) {
            if (rb1.isChecked()) {
                int input = Integer.valueOf(ed.getText().toString());
                double out = input / 24.0;
                out = Double.parseDouble(new DecimalFormat("#.0").format(out));
                Intent m = new Intent(this, MainActivity.class);
                m.putExtra("res", out);
                startActivity(m);
            } else if (rb2.isChecked()) {
                int input = Integer.valueOf(ed.getText().toString());
                double out = ((input * 2 / 3) * 0.029574);
                out = Double.parseDouble(new DecimalFormat("#.0").format(out));
                Intent m = new Intent(this, MainActivity.class);
                m.putExtra("res", out);
                startActivity(m);
            }
        }
    }
```
You have declared them (and at least for the widgets, you have inflated them) but they will not point to your data since they don't exist in the activity - once again, they were created by your fragment, not the activity.

**Comment by Andrew-Quebe** [comment] 2016-05-21 18:40
I think @avluis summed up everything I was going to say. Please reopen this issue if you have any further questions.

**Closed by Andrew-Quebe** 2016-05-21 18:40 UTC
Labels: question

**Comment by sunil512** [comment] 2016-05-23 12:53
That's the question I'm trying to explain @avluis  to you from last few comments. In the AppIntro activity the method DonePressed is there, not in my custom fragment class. From AppIntro class only its loading MainActivity. its not loading from my fragment. what I'm conveying you is, by using AppIntro can we make custom fragments which can get some data to MainActivity or only for displaying the data

**Comment by avluis** [comment] 2016-05-23 15:42
I already know and understand what the issue is, so please take the time to go over the response I gave you.
Do I need to highlight once again: `it can be done, but you, the programmer, must do so`.
