### ISSUE TITLE
If back button is pressed in the first slide it returns to the MainActivity 

### ISSUE THREAD

**Issue by Prakashk141** [paolorotolo/AppIntro#540] opened 2018-06-03 13:02 UTC
**AppIntro Version**: 4.2.3

**Device/Android Version**: 7.1.2

If the user presses the back button when the first slide comes it takes directly to the MainActivity instead of exiting the app.

**Comment by noam1023** [comment] 2018-10-04 09:20
Pressing the Back cause the activity to finish and return to the previous activity in the task. You probably started the AppIntro activity from MainActivity, so this is normal behavior

**Comment by cortinico** [comment] 2018-10-08 23:08
Closing as this is not an issue but the intended behavior @Prakashk141

**Closed by cortinico** 2018-10-08 23:08 UTC
