### ISSUE TITLE
Transform background color while sliding

### ISSUE THREAD

**Issue by nowke** [PaoloRotolo/AppIntro#85] opened 2015-09-16 17:23 UTC
How to transform the Fragments' background color according to the percentage of swipe, like in Google Apps? (Drive, Docs etc.) 

Similar approach is done in [TakeOffAndroid](https://github.com/TakeoffAndroid/AppIntroAnimation)

**Comment by msathis** [comment] 2015-09-28 13:30
I have added an example in https://github.com/PaoloRotolo/AppIntro/issues/80

**Comment by Andrew-Quebe** [comment] 2015-10-07 22:20
Duplicate of #80.

**Closed by Andrew-Quebe** 2015-10-07 22:20 UTC
Labels: duplicate
