### ISSUE TITLE
AppIntroFragment.newInstance() not using background color passed in

### ISSUE THREAD

**Issue by rajohns08** [PaoloRotolo/AppIntro#61] opened 2015-07-27 23:43 UTC
In CustomIntro.java you have

    addSlide(AppIntroFragment.newInstance("Title here", "Description here...\nYeah, I've added this fragment programmatically",
                R.drawable.ic_slide1, R.color.material_blue_grey_800));

but the color you passed in is not being used for the background. I have tried this in my own app and the color I pass int still doesn't work either. I am on nexus 5 emulator running API 21.

**Comment by PaoloRotolo** [comment] 2015-07-29 16:00
Hi @rajohns08, I can't reproduce this bug on my emulator/device.

Try to pass "Color.parseColor("#FFFFFF")" as parameter: is the background white?

**Comment by porokoro** [comment] 2015-07-29 17:03
Have you tried passing the resolved color? (```Context.getResources().getColor(int)```)

In the code you provided you pass the resource reference into ```AppIntroFragment.newInstance(String, String, int, int)```. I think it is shown wrong in the sample app. Internally the color is set with ```View.setBackgroundColor(int)``` which takes a resolved int for the color but the compiler doesn't complain because the reference to a color resource is an int as well.

**Comment by PaoloRotolo** [comment] 2015-07-29 17:05
@porokoro I don't know, anyway the sample app works fine on my device :/

**Comment by porokoro** [comment] 2015-07-29 18:38
@PaoloRotolo I was referencing to the state of the library when the issue was opened. After the commit [aea9a87](https://github.com/PaoloRotolo/AppIntro/commit/aea9a87bec624c6db334c924f3753e5ca4679516) the sample should work fine because a resource reference isn't passed as argument anymore.

Even before the commit it worked but with the wrong color. That is because a resource reference is just a simple integer and whatever number the compiler gave it is used instead of the color defined for that reference.
You can see that behavior in the sample app from the Play Store. The custom layout has a color, but that is not ```R.color.material_blue_grey_800``` (#37474F).

**Comment by PaoloRotolo** [comment] 2015-07-30 20:12
Ah, @porokoro I got it now :\
I thought #374745 was the right color (material_blue_grey).

Anyway, thank you all. Closing...

**Closed by PaoloRotolo** 2015-07-30 20:12 UTC
Labels: under investigation
